repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-yaml
          - id: check-merge-conflict
          - id: debug-statements
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/crate-ci/typos
      rev: v1.50.1
      hooks:
          - id: typos

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.9
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]
            files: \.py$
          - id: ruff-format
            files: \.py$

    - repo: local
      hooks:
          - id: yarn-lint
            name: yarn lint
            entry: yarn lint
            language: system
            files: \.(js|jsx|ts|tsx|mjs|cjs|vue|svelte)$
            exclude: ^(vendor/|node_modules/|\.yarn/)
            pass_filenames: false

          - id: yarn-format
            name: yarn format
            entry: yarn format
            language: system
            files: \.(js|jsx|ts|tsx|mjs|cjs|json|html|css|scss|less|vue|svelte|md|ya?ml)$
            exclude: ^(vendor/|node_modules/|\.yarn/)
            pass_filenames: false
