name: pre-commit

on:
    pull_request:
    push:
        branches: [main]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.14"

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: "24"

            - name: Enable Corepack
              run: corepack enable

            - name: Install JS dependencies
              run: yarn install --immutable

            - name: Run pre-commit hooks
              uses: pre-commit/action@v3.0.1
